pipeline {
  agent {
    docker {
      args '-v /var/run/docker.sock:/var/run/docker.sock -v ${WORKSPACE}:/opt/ssfs/shared -u root -it --name om-base'
      image 'mycluster.icp:8500/default/om-build:latest'
    }

  }
  stages {
    stage('Copy') {
      steps {
        echo 'Copy files to build image'
        sh 'ls'
      }
    }
  }
}
